name: CI

on: push

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Ultralisp
        run: ros -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'
      - name: Install Qlot
        run: ros install fukamachi/qlot
      - name: Install SBLint
        run: ros install cxxxr/sblint
      - name: Make Qlot environment
        run: touch qlfile && ~/.roswell/bin/qlot install
      - name: Run linter
        run: ~/.roswell/bin/qlot exec sblint
